/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import pkg30499854_shop.Clothing;
import pkg30499854_shop.DBManager;
import pkg30499854_shop.Footwear;
import pkg30499854_shop.Product;
import pkg30499854_shop.Staff;

/**
 *
 * @author yulii
 */
public class EditProduct extends javax.swing.JFrame {
    private static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAllProducts.class.getName());
    private Staff loggedInStaff;
    private Product productToEdit;

    /**
     * Creates new form EditProducts
     */
    public EditProduct(Product p, Staff st) {
        loggedInStaff = st;
        productToEdit = p;
        initComponents();
        
        //display the info on the page
        txt_ProductId.setText(String.valueOf(productToEdit.getProductId()));
        txt_ProductName.setText(productToEdit.getProductName());
        txt_Price.setText(String.valueOf(productToEdit.getPrice()));
        txt_StockLvl.setText(String.valueOf(productToEdit.getStockLevel()));
        
        //check for different types to add another data
        if(productToEdit.getClass().getName().equals("pkg30499854_shop.Clothing"))
        {
            //cast product as clothing
            //convertion is a bit better than casting
            Clothing c = (Clothing) productToEdit;
            //showing the info on the page
            lbl_addInfo.setText("Measurment:");
            txt_HiddenField.setText(String.valueOf(c.getmeasurment()));
        }
        else if (productToEdit.getClass().getName().equals("pkg30499854_shop.Footwear"))
        {
            //cast product to footwear
            Footwear f = (Footwear) productToEdit;
            //show information on the page
            lbl_addInfo.setText("Size:");
            txt_HiddenField.setText(String.valueOf(f.getSize()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_ProductName = new javax.swing.JTextField();
        txt_Price = new javax.swing.JTextField();
        txt_StockLvl = new javax.swing.JTextField();
        txt_ProductId = new javax.swing.JTextField();
        txt_HiddenField = new javax.swing.JTextField();
        lbl_addInfo = new javax.swing.JLabel();
        btn_Back = new javax.swing.JButton();
        btn_submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_Confirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Product ID");

        jLabel2.setText("Product Name");

        jLabel3.setText("Price £");

        jLabel4.setText("Stock Level");

        txt_ProductId.setEditable(false);

        lbl_addInfo.setText("Additional Information");

        btn_Back.setText("Back To Product Selection");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        btn_submit.setText("SUBMIT");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel5.setText("EDIT PRODUCT DETAILS");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_addInfo)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_StockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_HiddenField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btn_submit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btn_Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_Confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_ProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_StockLvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_HiddenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_addInfo))
                .addGap(18, 18, 18)
                .addComponent(btn_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Confirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        StaffProductPage stp = new StaffProductPage(loggedInStaff);
        stp.setVisible(true);
        this.setVisible(false);
                
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        
        //empty fields check
        if (txt_ProductName.getText().trim().isEmpty() ||
            txt_Price.getText().trim().isEmpty() ||
            txt_StockLvl.getText().trim().isEmpty())
        {
            lbl_Confirmation.setText("You've left something blank, check it again!");
            return;
        }

        //get the information from fields
        String productName = txt_ProductName.getText();
        double price = Double.parseDouble(txt_Price.getText());
        int stockLevel = Integer.parseInt(txt_StockLvl.getText());
        
        //set entered information for product 
        productToEdit.setProductName(productName);
        productToEdit.setPrice(price);
        productToEdit.setStockLevel(stockLevel);
        
        //check for different types for specific data
        if(productToEdit.getClass().getName().equals("pkg30499854_shop.Clothing"))
        {
            //get mesurment form fieds on the form
            String measurment = txt_HiddenField.getText();
            //cast product as clothing
            Clothing c = (Clothing) productToEdit;
            //set products manager measurment from entered data
            c.setmeasurment(measurment);
        }
        else if (productToEdit.getClass().getName().equals("pkg30499854_shop.Footwear"))
        {
            //get size from fields on the form
            int size = Integer.parseInt(txt_HiddenField.getText());
            //cast product to footwear
            Footwear f = (Footwear) productToEdit;
            //set products size from enetred data
            f.setSize(size);
            if (size < 0)
            {
            lbl_Confirmation.setText("Price, Stock and Size cannot be negative!");
            return;
            } 
        }

        // negative value check
        if (price < 0 || stockLevel < 0 )
        {
            lbl_Confirmation.setText("Price and Stock cannot be negative!");
            return;
        }

        // when ALL checks pass update product
        productToEdit.setProductName(txt_ProductName.getText().trim());
        productToEdit.setPrice(price);
        productToEdit.setStockLevel(stockLevel);

        DBManager db = new DBManager();
        db.editProduct(productToEdit);

        lbl_Confirmation.setText("The Product has been updated successfully!");

        
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
            //    new EditProduct().setVisible(true);
           // }
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbl_Confirmation;
    private javax.swing.JLabel lbl_addInfo;
    private javax.swing.JTextField txt_HiddenField;
    private javax.swing.JTextField txt_Price;
    private javax.swing.JTextField txt_ProductId;
    private javax.swing.JTextField txt_ProductName;
    private javax.swing.JTextField txt_StockLvl;
    // End of variables declaration//GEN-END:variables
}
