/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import pkg30499854_shop.DBManager;
import pkg30499854_shop.Product;
import pkg30499854_shop.Staff;

/**
 *
 * @author yulii
 */
public class StaffProductPage extends javax.swing.JFrame {
    private static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAllProducts.class.getName());
    private Staff loggedInStaff;
    private HashMap <Integer, Product> allProducts;
    
    /**
     * Creates new form ViewAllProducts
     */
    public StaffProductPage(Staff st) {
        loggedInStaff = st;
        DBManager db = new DBManager();
        allProducts = db.loadProducts();
        initComponents();
    }
    /**
     * Creates new form StaffProductPage
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        btn_DeleteProduct = new javax.swing.JButton();
        lbl_PageName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(lstItems);

        btnBack.setText("Return to Staff Home");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btn_DeleteProduct.setText("Delete Product");
        btn_DeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteProductActionPerformed(evt);
            }
        });

        lbl_PageName.setText("Edit Products");

        jLabel1.setText("Products");

        jLabel2.setText("CATEGORIES");

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clothing", "Footwear" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        jButton3.setText("Edit Product");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_PageName)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_DeleteProduct)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lbl_PageName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_DeleteProduct)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        StaffHomePage staffpage = new StaffHomePage(loggedInStaff);
        staffpage.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        DefaultListModel productList = new DefaultListModel();

        //get a value selected
        String productCategorySelected = lstCategories.getSelectedValue().toString();

        //looping through a HashMap, entry type Map.Entry <Key, Value>
        //making HashMap iterable by .entrySet()
        for (Map.Entry<Integer, Product> productMapEntry : allProducts.entrySet())
        {
            //get actual prodect
            Product actualProduct = productMapEntry.getValue();
            //check if it equals to the selected clothes type
            if(actualProduct.getClass().getName().equals("pkg30499854_shop." + productCategorySelected))
            {
                productList.addElement(actualProduct);
            }
        }

        lstItems.setModel(productList);
        // TODO add your handling code here:
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btn_DeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteProductActionPerformed
        //chack what was selected
        if(lstItems.getSelectedIndex()!= -1)
        {
            //create object
            Object selectedProductObj = lstItems.getSelectedValue();
            //convert object to product
            Product selectedProduct = (Product)selectedProductObj;
            //new dbmanager object created
            DBManager db = new DBManager();
            //call delete Product method and pass product we're willing to delete
            db.deleteProduct(selectedProduct);
            
            //removing it from the model and list
            DefaultListModel productList = (DefaultListModel)lstItems.getModel();
            productList.remove(lstItems.getSelectedIndex());
            
            //remove it from a hashmap, so when updated, does not displayed on the list again
            allProducts.remove(selectedProduct.getProductId());

            //display success message
            jLabel1.setText("Product Was Removed");
        }
        else
        {
            //error message displayed
            jLabel1.setText("Error: Select Product to add first");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_DeleteProductActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //check what item was selected:
        if(lstItems.getSelectedIndex()!= -1)
        {
            //create object
            Object selectedProductObj = lstItems.getSelectedValue();
            //convert object to product
            Product selectedProduct = (Product)selectedProductObj;
            //create the call to edit page whilst passing product and logged in Manager
            EditProduct edPr = new EditProduct (selectedProduct, loggedInStaff);
            edPr.setVisible(true);
            this.setVisible(false);
        }
        else
        {
            //error message displayed
            jLabel1.setText("Error: Select Product to add first");
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffProductPage().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_DeleteProduct;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_PageName;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstItems;
    // End of variables declaration//GEN-END:variables
}
