/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultListModel;
import pkg30499854_shop.Customer;
import pkg30499854_shop.DBManager;
import pkg30499854_shop.Order;
import pkg30499854_shop.OrderLine;
import pkg30499854_shop.Product;

/**
 *
 * @author yulii
 */
public class ViewAllProducts extends javax.swing.JFrame {
    
    private static java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewAllProducts.class.getName());

    private HashMap <Integer, Product> allProducts;
    
    private Order currentOrder;
    
    private Customer loggedInCustomer;
    
    /**
     * Creates new form ViewAllProducts
     */
    public ViewAllProducts(Customer c) {
        loggedInCustomer = c;
        DBManager db = new DBManager();
        allProducts = db.loadProducts();
        initComponents();
        currentOrder = new Order();
    }
    
    public ViewAllProducts (Customer c, Order cOrder){
        loggedInCustomer = c;
        DBManager db = new DBManager();
        allProducts = db.loadProducts();
        initComponents();
        currentOrder = cOrder; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategories = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstItems = new javax.swing.JList<>();
        btnBack = new javax.swing.JButton();
        btnAddToBasket = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_ViewBasket = new javax.swing.JButton();
        lblConfirmation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Available Items");

        jLabel2.setText("CATEGORIES");

        lstCategories.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Clothing", "Footwear" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategories.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCategoriesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategories);

        jScrollPane2.setViewportView(lstItems);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddToBasket.setText("ADD TO BASKET");
        btnAddToBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToBasketActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantity:");

        jLabel4.setText("PRODUCTS");

        btn_ViewBasket.setText("View Basket");
        btn_ViewBasket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewBasketActionPerformed(evt);
            }
        });

        lblConfirmation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(138, 138, 138)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ViewBasket))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(btnAddToBasket))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel4)
                    .addComponent(btn_ViewBasket))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnAddToBasket))
                    .addComponent(lblConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstCategoriesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCategoriesValueChanged
        DefaultListModel productList = new DefaultListModel();
        //get a value selected
        String productCategorySelected = lstCategories.getSelectedValue().toString();
        //looping through a HashMap, entry type Map.Entry <Key, Value>
        //making HashMap iterable by .entrySet()
        for (Map.Entry<Integer, Product> productMapEntry : allProducts.entrySet())
        {
            //get actual product
            Product actualProduct = productMapEntry.getValue();
            //check if it equals to the selected clothes type
            if(actualProduct.getClass().getName().equals("pkg30499854_shop." + productCategorySelected))
            {
                productList.addElement(actualProduct);
            }
        }
        
        lstItems.setModel(productList);
// TODO add your handling code here:
    }//GEN-LAST:event_lstCategoriesValueChanged

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CustomerHomePage custHP = new CustomerHomePage(loggedInCustomer);
        custHP.setVisible(true);
        this.setVisible(false); 
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddToBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToBasketActionPerformed
        //checks if anything is selected and throws error message if nothing is selected
        if (lstItems.getSelectedIndex()==-1)
        {
            lblConfirmation.setText("Error: Select Product to add first");
        }
        else
        {
            //converts selected value into product type
            Object selectedProductObj = lstItems.getSelectedValue();
            Product selectedProduct = (Product) selectedProductObj;
            
            //checking if the product is already in the basket
            if(currentOrder.isInBasket(selectedProduct.getProductId())== true)
            {
                lblConfirmation.setText("Selected Product is Already in the Basket");
            }
            else
            {
                //cheking and converting entered quantity to integer
            int quantity = 0;
            try {
                quantity = Integer.parseInt(txtQuantity.getText());
            } catch (NumberFormatException e) {
                lblConfirmation.setText("Please enter a valid quantity!");
            }
            //checks if quantity is valid and not higher than stock lvl
            if(selectedProduct.getStockLevel() >= quantity && !txtQuantity.getText().trim().isEmpty())
            {
                //creates new orderLine where passes Product and Quantity
                OrderLine ol = new OrderLine(selectedProduct, quantity);
                //adds orderLine into current Order
                currentOrder.addOrderLine(ol);
                //confirmation message
                lblConfirmation.setText("Product is added to basket");
            }
            else
            {
                lblConfirmation.setText("Product is not available or you've entered not valid quantity");
            }
            } 
        }
    }//GEN-LAST:event_btnAddToBasketActionPerformed

    private void btn_ViewBasketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewBasketActionPerformed
        ViewBasket vb = new ViewBasket(loggedInCustomer, currentOrder);
        vb.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ViewBasketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllProducts().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToBasket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_ViewBasket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConfirmation;
    private javax.swing.JList<String> lstCategories;
    private javax.swing.JList<String> lstItems;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
