/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.Date;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import pkg30499854_shop.Customer;
import pkg30499854_shop.DBManager;
import pkg30499854_shop.Order;
import pkg30499854_shop.OrderLine;

/**
 *
 * @author yulii
 */
public class ViewBasket extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewBasket.class.getName());
    private Order currentOrder;
    private Customer loggedInCustomer;
    /**
     * Creates new form ViewBasket
     */
    public ViewBasket(Customer c,Order o) {
        loggedInCustomer = c;
        currentOrder = o;
        initComponents();
        
        DefaultTableModel productBasketModel = (DefaultTableModel)tblBasket.getModel();
        for(Map.Entry<Integer, OrderLine> olMapEntry : currentOrder.getOrderLines().entrySet())
        {
            OrderLine actualOrderLine = olMapEntry.getValue();
            //adds row with information from order, which was made o ViewAllProducts page
            productBasketModel.addRow(new Object[]
                        {actualOrderLine.getProduct().getProductId(), 
                        actualOrderLine.getProduct(),
                        "£" + actualOrderLine.getLineTotal(),
                        actualOrderLine.getquantity()}
            );
        }
        tblBasket.setModel(productBasketModel);
        txtTotal.setText("Total: " + currentOrder.calculateOrderTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBasket = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btn_BuyProducts = new javax.swing.JButton();
        btnRemoveProduct = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductId", "Product", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBasket);

        btnBack.setText("Back To Catalog");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btn_BuyProducts.setText("BUY NOW");
        btn_BuyProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuyProductsActionPerformed(evt);
            }
        });

        btnRemoveProduct.setText("Remove Selected Product");
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        txtTotal.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(65, 65, 65)
                        .addComponent(txtTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_BuyProducts)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRemoveProduct)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btn_BuyProducts)
                    .addComponent(txtTotal))
                .addGap(18, 18, 18)
                .addComponent(btnRemoveProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        ViewAllProducts vap = new ViewAllProducts(loggedInCustomer, currentOrder);
        vap.setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn_BuyProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuyProductsActionPerformed
        //set date when order was placed and status
        currentOrder.setOrderDate(new Date());
        currentOrder.setStatus("Placed");
        
        DBManager db= new DBManager();
        //pass current order and Username
        int orderId = db.writeOrder (currentOrder, loggedInCustomer.getUsername());
        //loop through order lines in current order
        for(Map.Entry<Integer, OrderLine> olMapEntry : currentOrder.getOrderLines().entrySet())
        {
            OrderLine actualOrderLine = olMapEntry.getValue();
            //write orderLines in DB
            db.writeOrderLines(actualOrderLine, orderId);
            //updates Availaibilite in DB
            db.updateProductAvailability(actualOrderLine);
        }
        
        //display confirmation page
        Order_Confirmation confirm = new  Order_Confirmation(loggedInCustomer, currentOrder);
        confirm.setVisible(true);
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_btn_BuyProductsActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        //get selected row
        int selectedRow = tblBasket.getSelectedRow();
        //check if any row was selected
        if (selectedRow  == -1)
        {
            //show error message if nothing is selected
            lblErrorMessage.setText("Error: Please Select A Product First");
        }
        else
        {
            //get the productId from the table
            int productId = Integer.parseInt(String.valueOf(tblBasket.getValueAt(selectedRow, 0)));
            //make a call to remove method within Order and passes found productId
            currentOrder.romoveOrderLine(productId);
            //success message
            lblErrorMessage.setText("Product Successfully Removed!");
            //Update table om the basket form
            DefaultTableModel basketModel = (DefaultTableModel) tblBasket.getModel();
            basketModel.removeRow(selectedRow);
            tblBasket.setModel(basketModel);
            //update total on the screen
            txtTotal.setText("Total: "+currentOrder.calculateOrderTotal());
        }
// TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new ViewBasket().setVisible(true);
            //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JButton btn_BuyProducts;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JTable tblBasket;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
